name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: '🧬 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
  - title: '🏎 Performance Tweaks'
    labels:
      - 'performance'
  - title: '🎨 Style Tweaks'
    labels:
      - 'style tweak'
  - title: '⚙️ REST API Changes'
    labels:
      - 'api'
  - title: '⚠️ Deprecation'
    labels:
        - 'deprecation'
  - title: '📘 Documentation'
    labels:
      - 'documentation'
  - title: '🧹 Cleanup'
    labels:
      - 'cleanup'
  - title: '👷‍♀️ Testing, Configuration & Deployment'
    labels:
      - 'test'
      - 'devops'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES

  ## 🕵️‍♀️ Full commit logs

  - https://github.com/oncokb/oncokb-transcript/compare/$PREVIOUS_TAG...v$NEXT_MINOR_VERSION

