[[redirects]]
  from = "/websocket"
  to = "https://beta.curation.oncokb.org/websocket"

[[redirects]]
  from = "/api/*"
  to = "https://beta.curation.oncokb.org/api/:splat"
status = 200

[[redirects]]
  from = "/oidc/*"
  to = "https://beta.curation.oncokb.org/oidc/:splat"
  status = 200

[[redirects]]
  from = "/legacy-api/*"
  to = "https://beta.curation.oncokb.org/legacy-api/:splat"

[[redirects]]
  from = "/services/*"
  to = "https://beta.curation.oncokb.org/services/:splat"

[[redirects]]
  from = "/management/*"
  to = "https://beta.curation.oncokb.org/management/:splat"

[[redirects]]
  from = "/v3/api-docs/*"
  to = "https://beta.curation.oncokb.org/v3/api-docs/:splat"

[[redirects]]
  from = "/h2-console/*"
  to = "https://beta.curation.oncokb.org/h2-console/:splat"

[[redirects]]
  from = "/oauth2/*"
  to = "https://beta.curation.oncokb.org/oauth2/:splat"
  status = 200

[[redirects]]
  from = "/login/*"
  to = "https://beta.curation.oncokb.org/login/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "https://beta.curation.oncokb.org/auth/:splat"

