# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  keycloak-db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - kc-db:/var/lib/mysql
    networks:
      - kc-network
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.1
    command: start-dev
    #volumes:
    #- ./realm-config:/opt/bitnami/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      #KEYCLOAK_EXTRA_ARGS_PREPENDED: --import-realm
      #KEYCLOAK_BIND_ADDRESS: keycloak-db
    depends_on:
      - keycloak-db
    networks:
      - kc-network

    ports:
      - 8080:8080
volumes:
  kc-db:
networks:
  kc-network:
