export enum AlterationType {
  GENOMIC_CHANGE = 'GENOMIC_CHANGE',

  CDNA_CHANGE = 'CDNA_CHANGE',

  PROTEIN_CHANGE = 'PROTEIN_CHANGE',

  MUTATION = 'MUTATION',

  COPY_NUMBER_ALTERATION = 'COPY_NUMBER_ALTERATION',

  STRUCTURAL_VARIANT = 'STRUCTURAL_VARIANT',

  ANY = 'ANY',

  UNKNOWN = 'UNKNOWN',

  NA = 'NA',
}
