export enum ArticleType {
  PUBMED = 'PUBMED',

  ABSTRACT = 'ABSTRACT',

  REFERENCE = 'REFERENCE',

  FDADRUG_LETTER = 'FDADRUG_LETTER',

  FDADRUG_LABEL = 'FDADRUG_LABEL',

  FDADRUG_SUMMARY = 'FDADRUG_SUMMARY',

  FDADRUG_SUMMARY_REVIEW = 'FDADRUG_SUMMARY_REVIEW',
}
