export enum CategoricalAlterationType {
  ONCOKB_MUTATIONS = 'ONCOKB_MUTATIONS',

  GAIN_OF_FUNCTION_MUTATIONS = 'GAIN_OF_FUNCTION_MUTATIONS',

  LOSS_OF_FUNCTION_MUTATIONS = 'LOSS_OF_FUNCTION_MUTATIONS',

  SWITCH_OF_FUNCTION_MUTATIONS = 'SWITCH_OF_FUNCTION_MUTATIONS',

  VUS = 'VUS',

  TRUNCATING_MUTATIONS = 'TRUNCATING_MUTATIONS',

  FUSIONS = 'FUSIONS',

  AMPLIFICATION = 'AMPLIFICATION',

  DELETION = 'DELETION',

  PROMOTER = 'PROMOTER',

  WILDTYPE = 'WILDTYPE',
}
