export enum FlagTypeEnum {
  GENE_TYPE = 'GENE_TYPE',
  GENE_PANEL = 'GENE_PANEL',
  TRANSCRIPT = 'TRANSCRIPT',
  DRUG = 'DRUG',
  HOTSPOT = 'HOTSPOT',
  ALTERATION_CATEGORY = 'ALTERATION_CATEGORY',
}
