export enum GenePanelFlagEnum {
  ONCOKB = 'ONCOKB',

  MSK_IMPACT_505 = 'MSK_IMPACT_505',

  MSK_ACCESS = 'MSK_ACCESS',

  MSK_HEME = 'MSK_HEME',

  VOGELSTEIN = 'VOGELSTEIN',

  CGC_T1 = 'CGC_T1',

  FOUNDATION_ONE = 'FOUNDATION_ONE',

  FOUNDATION_HEME = 'FOUNDATION_HEME',

  TEMPUS_XT = 'TEMPUS_XT',

  TEMPUS_XR = 'TEMPUS_XR',

  TEMPUS_XF = 'TEMPUS_XF',

  TEMPUS_XG = 'TEMPUS_XG',

  TEMPUS_XG_PLUS = 'TEMPUS_XG_PLUS',

  TEMPUS_XE = 'TEMPUS_XE',

  GUARDANT_360 = 'GUARDANT_360',

  ONCOMINE_DX = 'ONCOMINE_DX',

  ONCOMINE_CA_V3 = 'ONCOMINE_CA_V3',

  ONCOMINE_CA_PLUS = 'ONCOMINE_CA_PLUS',

  CARIS_MI = 'CARIS_MI',

  TRUSIGHT_ONCOLOGY_500 = 'TRUSIGHT_ONCOLOGY_500',
}
