export enum InfoType {
  NCIT_VERSION = 'NCIT_VERSION',

  GENE_VERSION = 'GENE_VERSION',

  ONCOKB_TRANSCRIPT_VERSION = 'ONCOKB_TRANSCRIPT_VERSION',

  MANE_TRANSCRIPT_VERSION = 'MANE_TRANSCRIPT_VERSION',

  ENSEMBL_VERSION = 'ENSEMBL_VERSION',
}
