export enum TranscriptFlagEnum {
  MANE_SELECT = 'MANE_SELECT',

  MANE_PLUS_CLINICAL = 'MANE_PLUS_CLINICAL',

  GN_CANONICAL = 'GN_CANONICAL',

  ONCOKB = 'ONCOKB',

  ENSEMBL_CANONICAL = 'ENSEMBL_CANONICAL',
}
