package org.mskcc.oncokb.curation.domain.enumeration;

public enum EvidenceType {
    GENE_SUMMARY,
    MUTATION_SUMMARY,
    TUMOR_TYPE_SUMMARY,
    GENE_TUMOR_TYPE_SUMMARY,
    PROGNOSTIC_SUMMARY,
    DIAGNOSTIC_SUMMARY,
    GENE_BACKGROUND,
    ONCOGENIC,
    MUTATION_EFFECT,
    VUS,
    PROGNOSTIC_IMPLICATION,
    DIAGNOSTIC_IMPLICATION,
    STANDARD_THERAPEUTIC_IMPLICATIONS_FOR_DRUG_SENSITIVITY,
    STANDARD_THERAPEUTIC_IMPLICATIONS_FOR_DRUG_RESISTANCE,
    INVESTIGATIONAL_THERAPEUTIC_IMPLICATIONS_DRUG_SENSITIVITY,
    INVESTIGATIONAL_THERAPEUTIC_IMPLICATIONS_DRUG_RESISTANCE,
}
