name: Build/Push docker image
on:
  workflow_dispatch:
      inputs:
        tag-name:
          description: "Tag name to use for the image must start with a v"
          required: true
          type: string
  release:
    types: [ published ]
jobs:
  main:
    if: github.repository == 'oncokb/oncokb-transcript'
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install node.js packages
        run: npm install
      - name: Package application with Jib
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          TAG_NAME: ${{ inputs.tag-name || github.event.release.tag_name }}
          REPOSITORY: mskcc/oncokb-transcript
        run: |
          ./mvnw -ntp package -Pprod verify jib:build \
          -DskipTests \
          -Djib.to.image="${REPOSITORY}:${TAG_NAME:1}" \
          -Djib.to.auth.username=$DOCKER_USERNAME \
          -Djib.to.auth.password=$DOCKER_PASSWORD
