name: Build/Push docker image
on:
  workflow_dispatch:
      inputs:
        tag-name:
          description: "Tag name to use for the image must start with a v"
          required: true
          type: string
  release:
    types: [ published ]
jobs:
  main:
    if: github.repository == 'oncokb/oncokb-transcript'
    name: Build and Push
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ inputs.tag-name || github.ref }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Install node.js packages
        run: yarn install
      - name: Package application with Jib
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          TAG_NAME: ${{ inputs.tag-name || github.event.release.tag_name }}
          REPOSITORY: ${{ github.repository }}
        run: |
          ./mvnw -ntp package -Pprod verify jib:build \
          -DskipTests \
          -Djib.to.image="mskcc/oncokb-curation:${TAG_NAME:1}" \
          -Djib.to.auth.username=$DOCKER_USERNAME \
          -Djib.to.auth.password=$DOCKER_PASSWORD

      - name: Create a Sentry.io release in oncokb-curation-website
        uses: getsentry/action-release@v1.7.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: memorial-sloan-kettering
          SENTRY_PROJECT: oncokb-curation-website
        with:
          version: ${{ env.VERSION }}
          environment: production
          version_prefix: oncokb-curation-website-
          sourceMapOptions: '{"include": ["target/classes/static/app"]}'

      - name: Create a Sentry.io release in oncokb-curation-backend
        uses: getsentry/action-release@v1.7.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: memorial-sloan-kettering
          SENTRY_PROJECT: oncokb-curation-backend
        with:
          version: ${{ env.VERSION }}
          environment: production
          version_prefix: oncokb-curation-backend-
